# Generated by Django 4.2.11 on 2025-09-15 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/description of the image', max_length=100)),
                ('image_type', models.CharField(choices=[('logo', 'Logo'), ('banner', 'Banner'), ('background', 'Background')], default='logo', max_length=20)),
                ('image', models.ImageField(help_text='Upload navbar image', upload_to='navbar/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is currently active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navbar Image',
                'verbose_name_plural': 'Navbar Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
