# Generated by Django 4.2.11 on 2025-09-15 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_navbarimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title of the slide', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or location', max_length=300)),
                ('description', models.TextField(help_text='Detailed description')),
                ('image', models.ImageField(help_text='Slide background image', upload_to='carousel/')),
                ('button_text', models.CharField(default='More Details', help_text='Button text', max_length=50)),
                ('button_url', models.URLField(blank=True, help_text='Button link URL')),
                ('slide_type', models.CharField(choices=[('property', 'Property'), ('project', 'Project'), ('promotional', 'Promotional')], default='property', max_length=20)),
                ('background_color', models.CharField(default='#1e40af', help_text='Background gradient color (hex)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is currently active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
