# Generated by Django 4.2.11 on 2025-09-15 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_carouselslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('area', models.CharField(help_text='Area in katha/bigha', max_length=100)),
                ('location', models.CharField(help_text='Full location address', max_length=300)),
                ('division', models.CharField(choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong'), ('rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('barisal', 'Barisal'), ('sylhet', 'Sylhet'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh')], default='dhaka', max_length=20)),
                ('district', models.CharField(help_text='District name', max_length=100)),
                ('area_name', models.CharField(help_text='Specific area/upazila', max_length=100)),
                ('description', models.TextField(help_text='Project description')),
                ('image', models.ImageField(help_text='Project image', upload_to='land_properties/')),
                ('project_status', models.CharField(choices=[('ongoing', 'On Going'), ('completed', 'Completed'), ('upcoming', 'Up Coming')], default='ongoing', max_length=20)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use')], default='residential', max_length=20)),
                ('price_per_katha', models.DecimalField(blank=True, decimal_places=2, help_text='Price per katha', max_digits=12, null=True)),
                ('total_plots', models.PositiveIntegerField(blank=True, help_text='Total number of plots', null=True)),
                ('available_plots', models.PositiveIntegerField(blank=True, help_text='Available plots', null=True)),
                ('amenities', models.TextField(blank=True, help_text='Available amenities')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured project')),
                ('is_active', models.BooleanField(default=True, help_text='Active project')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Land Property',
                'verbose_name_plural': 'Land Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
