# Generated by Django 4.2.11 on 2025-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_landproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('land', 'Land Property'), ('commercial', 'Commercial Property'), ('other', 'Other')], max_length=20)),
                ('budget', models.CharField(blank=True, choices=[('under-50', 'Under 50 Lakh'), ('50-100', '50 Lakh - 1 Crore'), ('100-200', '1 Crore - 2 Crore'), ('200-500', '2 Crore - 5 Crore'), ('above-500', 'Above 5 Crore')], max_length=20)),
                ('message', models.TextField()),
                ('newsletter_subscription', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
