# Generated by Django 4.2.11 on 2025-09-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyProject',
        ),
    ]
