# Generated by Django 4.2.11 on 2025-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_unused_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='slide_type',
            field=models.CharField(choices=[('property', 'Property'), ('project', 'Project'), ('promotional', 'Promotional'), ('hero', 'Hero'), ('feature', 'Feature'), ('service', 'Service'), ('location', 'Location'), ('testimonial', 'Testimonial')], default='property', max_length=20),
        ),
    ]
