# Generated by Django 4.2.11 on 2025-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_update_carousel_slide_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Slide background image', null=True, upload_to='carousel/'),
        ),
    ]
