# Generated by Django 5.2.6 on 2025-09-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_carouselslide_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='title',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='slide_type',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='background_color',
        ),
    ]
