# Generated by Django 5.2.6 on 2025-09-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20250920_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='title',
            field=models.CharField(default='Default Title', help_text='Main title of the slide', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='description',
            field=models.TextField(default='Default Description', help_text='Detailed description'),
            preserve_default=False,
        ),
    ]
